package com.testapp.demo.mapper;

import com.testapp.demo.entity.DemoTable;
import java.util.List;

public interface DemoTableMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo_table
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    DemoTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table demo_table
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    List<DemoTable> selectAll();
}