package com.testapp.demo.entity;

public class DemoTable {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.id
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.name
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.age
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    private Integer age;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column demo_table.sex
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    private Boolean sex;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.id
     * @return  the value of demo_table.id
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.id
     * @param id  the value for demo_table.id
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.name
     * @return  the value of demo_table.name
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.name
     * @param name  the value for demo_table.name
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.age
     * @return  the value of demo_table.age
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.age
     * @param age  the value for demo_table.age
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column demo_table.sex
     * @return  the value of demo_table.sex
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column demo_table.sex
     * @param sex  the value for demo_table.sex
     * @mbg.generated  Mon Jan 03 01:10:19 JST 2022
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }
}